/**
 * FIRS 55 Mandatory Fields Schema
 * Based on Nigerian Tax Authority requirements for e-invoicing
 */

export interface FIRSField {
  name: string;
  path: string;
  type: 'string' | 'number' | 'date' | 'boolean' | 'object' | 'array';
  required: boolean;
  maxLength?: number;
  minLength?: number;
  pattern?: RegExp;
  description: string;
  example: any;
  validationRules?: Array<(value: any) => boolean | string>;
}

export const FIRS_MANDATORY_FIELDS: FIRSField[] = [
  // Header Information (10 fields)
  {
    name: 'invoiceNumber',
    path: 'invoice.invoiceNumber',
    type: 'string',
    required: true,
    maxLength: 50,
    pattern: /^[A-Za-z0-9\/\-]+$/,
    description: 'Unique invoice number assigned by seller',
    example: 'INV-2025-0001',
  },
  {
    name: 'invoiceType',
    path: 'invoice.invoiceType',
    type: 'string',
    required: true,
    pattern: /^(INVOICE|CREDIT_NOTE|DEBIT_NOTE)$/,
    description: 'Type of invoice document',
    example: 'INVOICE',
  },
  {
    name: 'invoiceCurrency',
    path: 'invoice.invoiceCurrency',
    type: 'string',
    required: true,
    maxLength: 3,
    minLength: 3,
    pattern: /^[A-Z]{3}$/,
    description: 'Currency code (ISO 4217)',
    example: 'NGN',
  },
  {
    name: 'invoiceIssueDate',
    path: 'invoice.invoiceIssueDate',
    type: 'date',
    required: true,
    description: 'Date when invoice was issued',
    example: '2025-02-24T10:30:00Z',
  },
  {
    name: 'invoiceDueDate',
    path: 'invoice.invoiceDueDate',
    type: 'date',
    required: true,
    description: 'Date when payment is due',
    example: '2025-03-24T23:59:59Z',
  },
  {
    name: 'invoiceSupplyDate',
    path: 'invoice.invoiceSupplyDate',
    type: 'date',
    required: false,
    description: 'Date when goods/services were supplied',
    example: '2025-02-23T00:00:00Z',
  },
  {
    name: 'invoiceNote',
    path: 'invoice.invoiceNote',
    type: 'string',
    required: false,
    maxLength: 500,
    description: 'Additional notes or instructions',
    example: 'Payment via bank transfer',
  },
  {
    name: 'invoicePeriodStart',
    path: 'invoice.invoicePeriodStart',
    type: 'date',
    required: false,
    description: 'Start of billing period',
    example: '2025-02-01T00:00:00Z',
  },
  {
    name: 'invoicePeriodEnd',
    path: 'invoice.invoicePeriodEnd',
    type: 'date',
    required: false,
    description: 'End of billing period',
    example: '2025-02-28T23:59:59Z',
  },
  {
    name: 'invoiceReferences',
    path: 'invoice.invoiceReferences',
    type: 'array',
    required: false,
    description: 'Related document references',
    example: ['PO-12345', 'QUOTE-6789'],
  },

  // Seller Information (12 fields)
  {
    name: 'sellerTIN',
    path: 'seller.tin',
    type: 'string',
    required: true,
    maxLength: 10,
    minLength: 10,
    pattern: /^\d{10}$/,
    description: 'Tax Identification Number (10 digits)',
    example: '1234567890',
  },
  {
    name: 'sellerName',
    path: 'seller.name',
    type: 'string',
    required: true,
    maxLength: 255,
    description: 'Legal business name',
    example: 'Elexsol Nigeria Ltd',
  },
  {
    name: 'sellerAddress',
    path: 'seller.address',
    type: 'string',
    required: true,
    maxLength: 500,
    description: 'Street address',
    example: '123 Marina Street',
  },
  {
    name: 'sellerCity',
    path: 'seller.city',
    type: 'string',
    required: true,
    maxLength: 100,
    description: 'City',
    example: 'Lagos Island',
  },
  {
    name: 'sellerState',
    path: 'seller.state',
    type: 'string',
    required: true,
    maxLength: 50,
    description: 'State',
    example: 'Lagos',
  },
  {
    name: 'sellerCountry',
    path: 'seller.country',
    type: 'string',
    required: true,
    maxLength: 2,
    minLength: 2,
    pattern: /^[A-Z]{2}$/,
    description: 'Country code (ISO 3166-1 alpha-2)',
    example: 'NG',
  },
  {
    name: 'sellerPostalCode',
    path: 'seller.postalCode',
    type: 'string',
    required: false,
    maxLength: 20,
    description: 'Postal/ZIP code',
    example: '101001',
  },
  {
    name: 'sellerEmail',
    path: 'seller.email',
    type: 'string',
    required: false,
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    description: 'Email address',
    example: 'billing@elexsol.com',
  },
  {
    name: 'sellerPhone',
    path: 'seller.phone',
    type: 'string',
    required: false,
    pattern: /^\+?[\d\s\-()]{10,}$/,
    description: 'Phone number',
    example: '+234 123 456 7890',
  },
  {
    name: 'sellerCACNumber',
    path: 'seller.cacNumber',
    type: 'string',
    required: false,
    pattern: /^[A-Z0-9]{6,}$/,
    description: 'Corporate Affairs Commission registration number',
    example: 'RC1234567',
  },
  {
    name: 'sellerVATNumber',
    path: 'seller.vatNumber',
    type: 'string',
    required: false,
    description: 'VAT registration number if different from TIN',
    example: 'VAT12345678',
  },
  {
    name: 'sellerBranch',
    path: 'seller.branch',
    type: 'string',
    required: false,
    description: 'Branch or division name',
    example: 'Head Office',
  },

  // Buyer Information (10 fields)
  {
    name: 'buyerTIN',
    path: 'buyer.tin',
    type: 'string',
    required: true,
    maxLength: 10,
    minLength: 10,
    pattern: /^\d{10}$/,
    description: 'Buyer Tax Identification Number',
    example: '9876543210',
  },
  {
    name: 'buyerName',
    path: 'buyer.name',
    type: 'string',
    required: true,
    maxLength: 255,
    description: 'Buyer business name',
    example: 'Customer Company Ltd',
  },
  {
    name: 'buyerAddress',
    path: 'buyer.address',
    type: 'string',
    required: true,
    maxLength: 500,
    description: 'Buyer address',
    example: '456 Broad Street',
  },
  {
    name: 'buyerCity',
    path: 'buyer.city',
    type: 'string',
    required: true,
    maxLength: 100,
    description: 'Buyer city',
    example: 'Ikeja',
  },
  {
    name: 'buyerState',
    path: 'buyer.state',
    type: 'string',
    required: true,
    maxLength: 50,
    description: 'Buyer state',
    example: 'Lagos',
  },
  {
    name: 'buyerCountry',
    path: 'buyer.country',
    type: 'string',
    required: true,
    maxLength: 2,
    minLength: 2,
    pattern: /^[A-Z]{2}$/,
    description: 'Buyer country code',
    example: 'NG',
  },
  {
    name: 'buyerPostalCode',
    path: 'buyer.postalCode',
    type: 'string',
    required: false,
    maxLength: 20,
    description: 'Buyer postal code',
    example: '100001',
  },
  {
    name: 'buyerEmail',
    path: 'buyer.email',
    type: 'string',
    required: false,
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    description: 'Buyer email',
    example: 'customer@example.com',
  },
  {
    name: 'buyerPhone',
    path: 'buyer.phone',
    type: 'string',
    required: false,
    description: 'Buyer phone',
    example: '+234 987 654 3210',
  },
  {
    name: 'buyerType',
    path: 'buyer.type',
    type: 'string',
    required: true,
    pattern: /^(BUSINESS|INDIVIDUAL|GOVERNMENT)$/,
    description: 'Type of buyer',
    example: 'BUSINESS',
  },

  // Line Items (15 fields)
  {
    name: 'lineNumber',
    path: 'lines[].lineNumber',
    type: 'number',
    required: true,
    description: 'Line item number',
    example: 1,
  },
  {
    name: 'itemCode',
    path: 'lines[].itemCode',
    type: 'string',
    required: false,
    maxLength: 50,
    description: 'Product/service code',
    example: 'PROD-001',
  },
  {
    name: 'itemDescription',
    path: 'lines[].itemDescription',
    type: 'string',
    required: true,
    maxLength: 500,
    description: 'Description of item/service',
    example: 'Software subscription - Enterprise Plan',
  },
  {
    name: 'quantity',
    path: 'lines[].quantity',
    type: 'number',
    required: true,
    minLength: 1,
    description: 'Quantity',
    example: 1,
  },
  {
    name: 'unitOfMeasure',
    path: 'lines[].unitOfMeasure',
    type: 'string',
    required: true,
    maxLength: 20,
    description: 'Unit of measure',
    example: 'unit',
  },
  {
    name: 'unitPrice',
    path: 'lines[].unitPrice',
    type: 'number',
    required: true,
    description: 'Price per unit',
    example: 1000000,
  },
  {
    name: 'discountAmount',
    path: 'lines[].discountAmount',
    type: 'number',
    required: true,
    default: 0,
    description: 'Discount amount for this line',
    example: 0,
  },
  {
    name: 'discountRate',
    path: 'lines[].discountRate',
    type: 'number',
    required: false,
    description: 'Discount percentage',
    example: 0,
  },
  {
    name: 'lineSubtotal',
    path: 'lines[].lineSubtotal',
    type: 'number',
    required: true,
    description: 'Subtotal before VAT (quantity * unitPrice - discount)',
    example: 1000000,
  },
  {
    name: 'vatRate',
    path: 'lines[].vatRate',
    type: 'number',
    required: true,
    description: 'VAT rate percentage',
    example: 7.5,
  },
  {
    name: 'vatAmount',
    path: 'lines[].vatAmount',
    type: 'number',
    required: true,
    description: 'VAT amount for this line',
    example: 75000,
  },
  {
    name: 'vatExemptionReason',
    path: 'lines[].vatExemptionReason',
    type: 'string',
    required: false,
    description: 'Reason if VAT exempt',
    example: 'Export service',
  },
  {
    name: 'exciseRate',
    path: 'lines[].exciseRate',
    type: 'number',
    required: false,
    description: 'Excise duty rate',
    example: 5,
  },
  {
    name: 'exciseAmount',
    path: 'lines[].exciseAmount',
    type: 'number',
    required: false,
    description: 'Excise duty amount',
    example: 50000,
  },
  {
    name: 'lineTotal',
    path: 'lines[].lineTotal',
    type: 'number',
    required: true,
    description: 'Total for line (lineSubtotal + vatAmount + exciseAmount)',
    example: 1075000,
  },

  // Totals (8 fields)
  {
    name: 'totalExclusiveVAT',
    path: 'totals.totalExclusiveVAT',
    type: 'number',
    required: true,
    description: 'Total amount excluding VAT',
    example: 1000000,
  },
  {
    name: 'totalVATAmount',
    path: 'totals.totalVATAmount',
    type: 'number',
    required: true,
    description: 'Total VAT amount',
    example: 75000,
  },
  {
    name: 'totalExciseAmount',
    path: 'totals.totalExciseAmount',
    type: 'number',
    required: true,
    default: 0,
    description: 'Total excise duty amount',
    example: 0,
  },
  {
    name: 'totalDiscountAmount',
    path: 'totals.totalDiscountAmount',
    type: 'number',
    required: true,
    default: 0,
    description: 'Total discount amount',
    example: 0,
  },
  {
    name: 'totalPayableAmount',
    path: 'totals.totalPayableAmount',
    type: 'number',
    required: true,
    description: 'Total amount payable',
    example: 1075000,
  },
  {
    name: 'amountInWords',
    path: 'totals.amountInWords',
    type: 'string',
    required: true,
    maxLength: 500,
    description: 'Amount in words',
    example: 'One million seventy-five thousand Naira only',
  },
  {
    name: 'totalInForeignCurrency',
    path: 'totals.totalInForeignCurrency',
    type: 'number',
    required: false,
    description: 'Total in foreign currency if applicable',
    example: null,
  },
  {
    name: 'exchangeRate',
    path: 'totals.exchangeRate',
    type: 'number',
    required: false,
    description: 'Exchange rate used',
    example: null,
  },

  // Payment & Delivery (5 fields)
  {
    name: 'paymentTerms',
    path: 'payment.paymentTerms',
    type: 'string',
    required: false,
    maxLength: 200,
    description: 'Payment terms description',
    example: 'Net 30 days',
  },
  {
    name: 'paymentMethod',
    path: 'payment.paymentMethod',
    type: 'string',
    required: true,
    pattern: /^(CASH|TRANSFER|CHEQUE|CARD|POS|OTHER)$/,
    description: 'Method of payment',
    example: 'TRANSFER',
  },
  {
    name: 'paymentReference',
    path: 'payment.paymentReference',
    type: 'string',
    required: false,
    description: 'Payment reference if prepaid',
    example: null,
  },
  {
    name: 'deliveryMethod',
    path: 'delivery.deliveryMethod',
    type: 'string',
    required: false,
    description: 'Method of delivery',
    example: 'Email',
  },
  {
    name: 'deliveryDate',
    path: 'delivery.deliveryDate',
    type: 'date',
    required: false,
    description: 'Date of delivery',
    example: null,
  },

  // Regulatory (5 fields)
  {
    name: 'qrCode',
    path: 'regulatory.qrCode',
    type: 'string',
    required: false,
    description: 'FIRS generated QR code',
    example: null,
  },
  {
    name: 'digitalSignature',
    path: 'regulatory.digitalSignature',
    type: 'string',
    required: false,
    description: 'JAdES digital signature',
    example: null,
  },
  {
    name: 'signatureDate',
    path: 'regulatory.signatureDate',
    type: 'date',
    required: false,
    description: 'Date of signing',
    example: null,
  },
  {
    name: 'irn',
    path: 'regulatory.irn',
    type: 'string',
    required: false,
    description: 'Invoice Reference Number from FIRS',
    example: null,
  },
  {
    name: 'csid',
    path: 'regulatory.csid',
    type: 'string',
    required: false,
    description: 'Communication Session ID',
    example: null,
  },
];

// Error codes from FIRS
export const FIRS_ERROR_CODES: Record<string, {
  code: string;
  message: string;
  description: string;
  resolution: string;
}> = {
  'E001': {
    code: 'E001',
    message: 'Invalid TIN',
    description: 'The Tax Identification Number provided is invalid or not found',
    resolution: 'Verify the TIN and ensure it is a valid 10-digit number',
  },
  'E002': {
    code: 'E002',
    message: 'Duplicate Invoice',
    description: 'An invoice with the same number already exists',
    resolution: 'Use a unique invoice number',
  },
  'E003': {
    code: 'E003',
    message: 'Missing Mandatory Field',
    description: 'One or more mandatory fields are missing',
    resolution: 'Check the validation response and provide all required fields',
  },
  'E004': {
    code: 'E004',
    message: 'Invalid VAT Calculation',
    description: 'VAT amount does not match the calculated amount',
    resolution: 'Ensure VAT is calculated correctly at 7.5%',
  },
  'E005': {
    code: 'E005',
    message: 'Certificate Expired',
    description: 'The digital certificate has expired',
    resolution: 'Renew your CSID certificate',
  },
  'E006': {
    code: 'E006',
    message: 'Invalid Signature',
    description: 'The digital signature is invalid',
    resolution: 'Verify the signing process and certificate',
  },
  'E007': {
    code: 'E007',
    message: 'Business Not Registered',
    description: 'The business is not registered for e-invoicing',
    resolution: 'Complete FIRS registration first',
  },
  'E008': {
    code: 'E008',
    message: 'Invoice Date Error',
    description: 'Invoice date cannot be in the future',
    resolution: 'Use current or past dates only',
  },
  'E009': {
    code: 'E009',
    message: 'Amount Mismatch',
    description: 'Total amount does not match sum of line items',
    resolution: 'Verify all calculations',
  },
  'E010': {
    code: 'E010',
    message: 'System Error',
    description: 'Internal FIRS system error',
    resolution: 'Retry after a few minutes',
  },
};

// VAT rates for Nigeria
export const VAT_RATES = {
  STANDARD: 7.5,
  ZERO: 0,
  EXEMPT: -1, // Special value for exempt items
};

// Nigerian states list
export const NIGERIAN_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue',
  'Borno', 'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu',
  'FCT - Abuja', 'Gombe', 'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina',
  'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo',
  'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara',
];
